# -*- coding: utf-8 -*-

{
    u'hr.payroll.payitem':
        '\t\t<!-- hr_payroll_payitem-->\n'
        '\t\t<record id="hr_payroll_payitem_%(code)s" model="hr.payroll.payitem">\n'
        '\t\t\t<field name="active" eval="%(active)s" />\n'
        '\t\t\t<field name="alias1">%(alias1)s</field>\n'
        '\t\t\t<field name="alias2">%(alias2)s</field>\n'
        '\t\t\t<field name="alias3">%(alias3)s</field>\n'
        '\t\t\t<field name="alias4">%(alias4)s</field>\n'
        '\t\t\t<field name="alias5">%(alias5)s</field>\n'
        '\t\t\t<field name="amount_python_compute">%(amount_python_compute)s</field>\n'
        '\t\t\t<field name="appears_on_payslip" eval="%(appears_on_payslip)s" />\n'
        '\t\t\t<field name="calculate_precision">%(calculate_precision)s</field>\n'
        '\t\t\t<field name="category" ref="%(category)s" />\n'
        '\t\t\t<field name="code">%(code)s</field>\n'
        't\t\t<field name="company_id" ref="%(company_id)s" />\n'
        '\t\t\t<field name="condition_python">%(condition_python)s</field>\n'
        '\t\t\t<field name="cumulative_item" eval="%(cumulative_item)s" />\n'
        '\t\t\t<field name="decimal_processing_mode">%(decimal_processing_mode)s</field>\n'
        '\t\t\t<field name="default_value">%(default_value)s</field>\n'
        '\t\t\t<field name="duplication_unallowed" eval="%(duplication_unallowed)s" />\n'
        '\t\t\t<field name="evaluation_sequence">%(evaluation_sequence)s</field>\n'
        '\t\t\t<field name="fixed_value">%(fixed_value)s</field>\n'
        '\t\t\t<field name="group_id" ref="%(group_id)s" />\n'
        '\t\t\t<field name="is_group_only" eval="%(is_group_only)s" />\n'
        '\t\t\t<field name="is_standard_group" eval="%(is_standard_group)s" />\n'
        '\t\t\t<field name="is_standard_payitem" eval="%(is_standard_payitem)s" />\n'
        '\t\t\t<field name="is_system_logic" eval="%(is_system_logic)s" />\n'
        '\t\t\t<field name="meta_data" ref="%(meta_data)s" />\n'
        '\t\t\t<field name="name">%(name)s</field>\n'
        '\t\t\t<field name="note">%(note)s</field>\n'
        '\t\t\t<field name="payitem_search">%(payitem_search)s</field>\n'
        '\t\t\t<field name="ref_payitem" ref="%(ref_payitem)s" />\n'
        '\t\t\t<field name="result_payitem_id" ref="%(result_payitem_id)s" />\n'
        '\t\t\t<field name="scope">%(scope)s</field>\n'
        '\t\t\t<field name="sequence">%(sequence)s</field>\n'
        '\t\t\t<field name="source">%(source)s</field>\n'
        '\t\t\t<field name="tax" ref="%(tax)s" />\n'
        '\t\t\t<field name="tax_type">%(tax_type)s</field>\n'
        '\t\t\t<field name="value_type">%(value_type)s</field>\n'
        '\n'
        '\t\t</record>\n'
}

{
    u'hr.payroll.payitem':
        '\t\t<!-- hr_payroll_payitem-->\n        '
        '\t\t<record id="hr_payroll_payitem_%(code)s" model="hr.payroll.payitem">\n        '
        '\t\t\t<field name="active" eval="%(active)s" />\n'
        '\t\t\t<field name="alias1">%(alias1)s</field>\n'
        '\t\t\t<field name="alias2">%(alias2)s</field>\n'
        '\t\t\t<field name="alias3">%(alias3)s</field>\n'
        '\t\t\t<field name="alias4">%(alias4)s</field>\n'
        '\t\t\t<field name="alias5">%(alias5)s</field>\n'
        '\t\t\t<field name="amount_python_compute">%(amount_python_compute)s</field>\n'
        '\t\t\t<field name="appears_on_payslip" eval="%(appears_on_payslip)s" />\n'
        '\t\t\t<field name="calculate_precision">%(calculate_precision)s</field>\n'
        '\t\t\t<field name="category" ref="%(category)s" />\n'
        '\t\t\t<field name="code">%(code)s</field>\n'
        '\t\t\t<field name="company_id" ref="%(company_id)s" />\n'
        '\t\t\t<field name="condition_python">%(condition_python)s</field>\n'
        '\t\t\t<field name="cumulative_item" eval="%(cumulative_item)s" />\n'
        '\t\t\t<field name="decimal_processing_mode">%(decimal_processing_mode)s</field>\n'
        '\t\t\t<field name="default_value">%(default_value)s</field>\n'
        '\t\t\t<field name="duplication_unallowed" eval="%(duplication_unallowed)s" />\n'
        '\t\t\t<field name="evaluation_sequence">%(evaluation_sequence)s</field>\n'
        '\t\t\t<field name="fixed_value">%(fixed_value)s</field>\n'
        '\t\t\t<field name="group_id" ref="%(group_id)s" />\n'
        '\t\t\t<field name="is_group_only" eval="%(is_group_only)s" />\n'
        '\t\t\t<field name="is_standard_group" eval="%(is_standard_group)s" />\n'
        '\t\t\t<field name="is_standard_payitem" eval="%(is_standard_payitem)s" />\n'
        '\t\t\t<field name="is_system_logic" eval="%(is_system_logic)s" />\n'
        '\t\t\t<field name="meta_data" ref="%(meta_data)s" />\n'
        '\t\t\t<field name="name">%(name)s</field>\n'
        '\t\t\t<field name="note">%(note)s</field>\n'
        '\t\t\t<field name="payitem_search">%(payitem_search)s</field>\n'
        '\t\t\t<field name="ref_payitem" ref="%(ref_payitem)s" />\n'
        '\t\t\t<field name="result_payitem_id" ref="%(result_payitem_id)s" />\n'
        '\t\t\t<field name="scope">%(scope)s</field>\n'
        '\t\t\t<field name="sequence">%(sequence)s</field>\n'
        '\t\t\t<field name="source">%(source)s</field>\n'
        '\t\t\t<field name="tax" ref="%(tax)s" />\n'
        '\t\t\t<field name="tax_type">%(tax_type)s</field>\n'
        '\t\t\t<field name="value_type">%(value_type)s</field>\n'
        '\n        '
        '\t\t</record>\n        '
}

{
    'hr.payroll.meta.data':
        '\t\t<!-- hr_payroll_meta_data-->\n        '
        '\t\t<record id="hr_payroll_meta_data_%(code)s" model="hr.payroll.meta.data">\n        '
        '\t\t\t<field name="active" eval="%(active)s" />\n'
        '\t\t\t<field name="category_id" ref="%(category_id)s" />\n'
        '\t\t\t<field name="code">%(code)s</field>\n\t\t\t<field name="description">%(description)s</field>\n\t\t\t<field name="is_necessary" eval="%(is_necessary)s" />\n\t\t\t<field name="is_only" eval="%(is_only)s" />\n\t\t\t<field name="name">%(name)s</field>\n\t\t\t<field name="parent_id" ref="%(parent_id)s" />\n\t\t\t<field name="tax_id" ref="%(tax_id)s" />\n\t\t\t<field name="value_type">%(value_type)s</field>\n\n        \t\t</record>\n        ', 'hr.payroll.group': '\t\t<!-- hr_payroll_group-->\n        \t\t<record id="hr_payroll_group_%(code)s" model="hr.payroll.group">\n        \t\t\t<field name="active" eval="%(active)s" />\n\t\t\t<field name="calculate_order">%(calculate_order)s</field>\n\t\t\t<field name="code">%(code)s</field>\n\t\t\t<field name="company_id" ref="%(company_id)s" />\n\t\t\t<field name="effective_date">%(effective_date)s</field>\n\t\t\t<field name="efficient_date">%(efficient_date)s</field>\n\t\t\t<field name="employee_filter_domain">%(employee_filter_domain)s</field>\n\t\t\t<field name="expired_date">%(expired_date)s</field>\n\t\t\t<field name="first_open_attendance_date">%(first_open_attendance_date)s</field>\n\t\t\t<field name="first_open_payroll_date">%(first_open_payroll_date)s</field>\n\t\t\t<field name="first_open_period_name">%(first_open_period_name)s</field>\n\t\t\t<field name="is_standard_group" eval="%(is_standard_group)s" />\n\t\t\t<field name="name">%(name)s</field>\n\t\t\t<field name="note">%(note)s</field>\n\t\t\t<field name="state">%(state)s</field>\n\t\t\t<field name="version">%(version)s</field>\n\t\t\t<field name="work_calendar_id" ref="%(work_calendar_id)s" />\n\n        \t\t</record>\n        ', 'reference.payitem': '\t\t<!-- reference_payitem-->\n        \t\t<record id="reference_payitem_%(code)s" model="reference.payitem">\n        \t\t\t<field name="active" eval="%(active)s" />\n\t\t\t<field name="code">%(code)s</field>\n\t\t\t<field name="company_id" ref="%(company_id)s" />\n\t\t\t<field name="constraint_term">%(constraint_term)s</field>\n\t\t\t<field name="description">%(description)s</field>\n\t\t\t<field name="name">%(name)s</field>\n\t\t\t<field name="option_active">%(option_active)s</field>\n\t\t\t<field name="ref_field" ref="%(ref_field)s" />\n\t\t\t<field name="ref_field_filter_value">%(ref_field_filter_value)s</field>\n\t\t\t<field name="ref_field_key" ref="%(ref_field_key)s" />\n\t\t\t<field name="ref_fixed_payitem" eval="%(ref_fixed_payitem)s" />\n\t\t\t<field name="ref_get_value_field" ref="%(ref_get_value_field)s" />\n\t\t\t<field name="ref_get_value_field_ttype">%(ref_get_value_field_ttype)s</field>\n\t\t\t<field name="ref_model_config_id" ref="%(ref_model_config_id)s" />\n\t\t\t<field name="ref_reference_model_name">%(ref_reference_model_name)s</field>\n\t\t\t<field name="reference_model_name">%(reference_model_name)s</field>\n\t\t\t<field name="reference_payitem_search">%(reference_payitem_search)s</field>\n\t\t\t<field name="value_type">%(value_type)s</field>\n\n        \t\t</record>\n        ', 'res.company': '\t\t<!-- res_company-->\n        \t\t<record id="res_company_%(code)s" model="res.company">\n        \t\t\t<field name="account_no">%(account_no)s</field>\n\t\t\t<field name="alert_follow">%(alert_follow)s</field>\n\t\t\t<field name="app_logo_url">%(app_logo_url)s</field>\n\t\t\t<field name="background_url">%(background_url)s</field>\n\t\t\t<field name="city">%(city)s</field>\n\t\t\t<field name="city_id" ref="%(city_id)s" />\n\t\t\t<field name="company_registry">%(company_registry)s</field>\n\t\t\t<field name="country_id" ref="%(country_id)s" />\n\t\t\t<field name="currency_id" ref="%(currency_id)s" />\n\t\t\t<field name="custom_footer" eval="%(custom_footer)s" />\n\t\t\t<field name="description">%(description)s</field>\n\t\t\t<field name="email">%(email)s</field>\n\t\t\t<field name="fax">%(fax)s</field>\n\t\t\t<field name="font" ref="%(font)s" />\n\t\t\t<field name="logo_url">%(logo_url)s</field>\n\t\t\t<field name="name">%(name)s</field>\n\t\t\t<field name="paperformat_id" ref="%(paperformat_id)s" />\n\t\t\t<field name="parent_id" ref="%(parent_id)s" />\n\t\t\t<field name="partner_code">%(partner_code)s</field>\n\t\t\t<field name="partner_id" ref="%(partner_id)s" />\n\t\t\t<field name="phone">%(phone)s</field>\n\t\t\t<field name="qr_code_url">%(qr_code_url)s</field>\n\t\t\t<field name="rml_footer">%(rml_footer)s</field>\n\t\t\t<field name="rml_footer_readonly">%(rml_footer_readonly)s</field>\n\t\t\t<field name="rml_header">%(rml_header)s</field>\n\t\t\t<field name="rml_header1">%(rml_header1)s</field>\n\t\t\t<field name="rml_header2">%(rml_header2)s</field>\n\t\t\t<field name="rml_header3">%(rml_header3)s</field>\n\t\t\t<field name="rml_paper_format">%(rml_paper_format)s</field>\n\t\t\t<field name="state_id" ref="%(state_id)s" />\n\t\t\t<field name="street">%(street)s</field>\n\t\t\t<field name="street2">%(street2)s</field>\n\t\t\t<field name="title">%(title)s</field>\n\t\t\t<field name="town_id" ref="%(town_id)s" />\n\t\t\t<field name="vat">%(vat)s</field>\n\t\t\t<field name="website">%(website)s</field>\n\t\t\t<field name="weixin_code">%(weixin_code)s</field>\n\t\t\t<field name="zip">%(zip)s</field>\n\n        \t\t</record>\n        ', 'hr.payroll.payitem.category': '\t\t<!-- hr_payroll_payitem_category-->\n        \t\t<record id="hr_payroll_payitem_category_%(code)s" model="hr.payroll.payitem.category">\n        \t\t\t<field name="company_id" ref="%(company_id)s" />\n\t\t\t<field name="name">%(name)s</field>\n\t\t\t<field name="note">%(note)s</field>\n\n        \t\t</record>\n        ', 'hr.payroll.tax': '\t\t<!-- hr_payroll_tax-->\n        \t\t<record id="hr_payroll_tax_%(code)s" model="hr.payroll.tax">\n        \t\t\t<field name="code">%(code)s</field>\n\t\t\t<field name="company_id" ref="%(company_id)s" />\n\t\t\t<field name="description">%(description)s</field>\n\t\t\t<field name="function_id" ref="%(function_id)s" />\n\t\t\t<field name="name">%(name)s</field>\n\n        \t\t</record>\n        ', u'hr.payroll.payitem': '\t\t<!-- hr_payroll_payitem-->\n        \t\t<record id="hr_payroll_payitem_%(code)s" model="hr.payroll.payitem">\n        \t\t\t<field name="active" eval="%(active)s" />\n\t\t\t<field name="alias1">%(alias1)s</field>\n\t\t\t<field name="alias2">%(alias2)s</field>\n\t\t\t<field name="alias3">%(alias3)s</field>\n\t\t\t<field name="alias4">%(alias4)s</field>\n\t\t\t<field name="alias5">%(alias5)s</field>\n\t\t\t<field name="amount_python_compute">%(amount_python_compute)s</field>\n\t\t\t<field name="appears_on_payslip" eval="%(appears_on_payslip)s" />\n\t\t\t<field name="calculate_precision">%(calculate_precision)s</field>\n\t\t\t<field name="category" ref="%(category)s" />\n\t\t\t<field name="code">%(code)s</field>\n\t\t\t<field name="company_id" ref="%(company_id)s" />\n\t\t\t<field name="condition_python">%(condition_python)s</field>\n\t\t\t<field name="cumulative_item" eval="%(cumulative_item)s" />\n\t\t\t<field name="decimal_processing_mode">%(decimal_processing_mode)s</field>\n\t\t\t<field name="default_value">%(default_value)s</field>\n\t\t\t<field name="duplication_unallowed" eval="%(duplication_unallowed)s" />\n\t\t\t<field name="evaluation_sequence">%(evaluation_sequence)s</field>\n\t\t\t<field name="fixed_value">%(fixed_value)s</field>\n\t\t\t<field name="group_id" ref="%(group_id)s" />\n\t\t\t<field name="is_group_only" eval="%(is_group_only)s" />\n\t\t\t<field name="is_standard_group" eval="%(is_standard_group)s" />\n\t\t\t<field name="is_standard_payitem" eval="%(is_standard_payitem)s" />\n\t\t\t<field name="is_system_logic" eval="%(is_system_logic)s" />\n\t\t\t<field name="meta_data" ref="%(meta_data)s" />\n\t\t\t<field name="name">%(name)s</field>\n\t\t\t<field name="note">%(note)s</field>\n\t\t\t<field name="payitem_search">%(payitem_search)s</field>\n\t\t\t<field name="ref_payitem" ref="%(ref_payitem)s" />\n\t\t\t<field name="result_payitem_id" ref="%(result_payitem_id)s" />\n\t\t\t<field name="scope">%(scope)s</field>\n\t\t\t<field name="sequence">%(sequence)s</field>\n\t\t\t<field name="source">%(source)s</field>\n\t\t\t<field name="tax" ref="%(tax)s" />\n\t\t\t<field name="tax_type">%(tax_type)s</field>\n\t\t\t<field name="value_type">%(value_type)s</field>\n\n        \t\t</record>\n        '}



